version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
     - 80:80
     - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/general.conf:/etc/nginx/general.conf:ro
      - ./nginx/security.conf:/etc/nginx/security.conf:ro
      - ./nginx/letsencrypt.conf:/etc/nginx/letsencrypt.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\""
    restart: unless-stopped
    depends_on:
      - certbot
      - dyndns
      - dash

  certbot:
    container_name: certbot
    image: certbot/certbot:arm32v6-v1.5.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  dyndns:
    container_name: dyndns
    build: ./dyndns
    env_file: .env.dyndns
    restart: unless-stopped

  dash:
    container_name: dash
    build: ./dash
    volumes:
      - ./data/temp.db:/data/temp.db
    environment:
      - SQLITE_DB=/data/temp.db
    restart: unless-stopped

  w1:
    container_name: w1
    build: ./w1
    volumes:
      - ./data/temp.db:/data/temp.db
    environment:
      - SQLITE_DB=/data/temp.db
    restart: unless-stopped

  bme280:
    container_name: bme280
    build: ./bme280
    volumes:
      - ./data/temp.db:/data/temp.db
    environment:
      - SQLITE_DB=/data/temp.db
    restart: unless-stopped

  pir:
    container_name: pir
    build: ./pir
    volumes:
      - ./data/temp.db:/data/temp.db
    environment:
      - SQLITE_DB=/data/temp.db
    restart: unless-stopped
